//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public byte[] update_date { get; set; }
        public string kar { get; set; }
    }
}
